name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - '@romanize-string/thai-romanizer@*' # only run when you push a version tag like v1.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # add macos-latest if needed
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pythainlp
        working-directory: packages/thai-romanizer/python

      - name: Build binary
        run: |
          pyinstaller --onefile python-thai-romanization.py
          mv dist/python-thai-romanization thai-${{ matrix.os == 'windows-latest' && 'win.exe' || (matrix.os == 'macos-latest' && 'mac' || 'linux') }}
        working-directory: packages/thai-romanizer/python

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: packages/thai-romanizer/python/thai-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}