name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - '@romanize-string/thai-romanizer@*' # only run when you push a version tag like v1.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # add macos-latest if needed
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pythainlp
        working-directory: packages/thai-romanizer/python

      - name: Build binary
        run: |
          pyinstaller --onefile python-thai-romanization.py
        working-directory: packages/thai-romanizer/python

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: packages/thai-romanizer/python/dist/**