name: Tag & Release (after Changesets version)

on:
  push:
    branches: 
      - release

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tag_and_release:
    # Only run when the merge commit contains "Version Packages"
    if: contains(github.event.head_commit.message, 'Version Packages')
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create tags & releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changed packages
        id: pkgs
        run: |
          # Find changed package.json files in this push compared to the previous SHA
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep -E '^packages/[^/]+/package.json$' || true)

          # Build a JSON array of { name, version, path } for changed packages
          echo "$CHANGED" | while read -r f; do
            [ -z "$f" ] && continue
            NAME=$(jq -r '.name' "$f")
            VER=$(jq -r '.version' "$f")
            echo "{\"name\":\"$NAME\",\"version\":\"$VER\",\"path\":\"$f\"}"
          done | jq -s '.' > /tmp/pkgs.json

          echo "packages=$(cat /tmp/pkgs.json)" >> "$GITHUB_OUTPUT"

      - name: Create tags and releases
        uses: actions/github-script@v7
        env:
          PKGS: ${{ steps.pkgs.outputs.packages }}
        with:
          script: |
            const pkgs = JSON.parse(process.env.PKGS || '[]');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            for (const p of pkgs) {
              if (!p.name || !p.version) continue;
              const tag = `${p.name}@${p.version}`;

              // Check if tag already exists
              try {
                await github.rest.git.getRef({ owner, repo, ref: `tags/${tag}` });
                // Tag exists; skip creating it
              } catch (e) {
                // Create lightweight tag pointing to this commit
                await github.rest.git.createRef({
                  owner, repo,
                  ref: `refs/tags/${tag}`,
                  sha: context.sha,
                });
              }

              // Try to create a GitHub Release (idempotent: skip if exists)
              try {
                await github.rest.repos.getReleaseByTag({ owner, repo, tag });
                // Release already exists; skip
              } catch (e) {
                await github.rest.repos.createRelease({
                  owner, repo,
                  tag_name: tag,
                  name: tag,
                  body: `Automated release created on version bump for \`${p.name}\`.\n\nSee package CHANGELOG for details.`,
                  draft: false,
                  prerelease: false
                });
              }
            }